POST http://localhost:8080/compra
Content-Type: application/json
//REALIZA UMA NOVA COMPRA DE UM CURSO

{
  "id": 1,
  "data": "28/09/2021",
  "valor": 50.0,
  "comprador": 2,
  "vendedor": 1,
  "curso": 1
}
###
